### ISSUE TITLE
Conflict with dimension mods. Player with die when coming back from mod dimension.

### ISSUE THREAD

**Issue by oraant** [TheCSDev/mc-no-unused-chunks#2]
Mods like Blue Skies, Dimensional Dungeons, facing same problem.

**Comment by TheCSDev** [comment]
Hello. Thank you for submitting an issue. Unfortunately, I did not understand what you were trying to say, so could you please explain in more detail? After downloading the mods myself and testing them, I found no issues myself, unless I am missing something? Please provide instructions on how to reproduce the issue, or screenshots showing the issue, or perhaps some debug logs or world files so I see what happened from there. Anything that would help me understand what the exact issue is.

Were you tring to say the player would die when returning from a modded dimension? If so, I did not manage to reproduce the issue.

**Comment by TheCSDev** [comment]
Sorry, but I will now close the issue, as I was not able to find any issues myself, and I got no reply. If there really is an issue. Please create another issue with a more detailed explaination.

**Comment by TheCSDev** [comment]
Sorry, was correcting the status of the issue.
