### ISSUE TITLE
Forge 1.19.2 Log Spam

### ISSUE THREAD

**Issue by ardissaps** [TheCSDev/mc-no-unused-chunks#4]
![image](https://user-images.githubusercontent.com/82106625/188043435-55e6fb2f-cf97-4ec6-8be2-69ee9a53a4eb.png)
https://mclo.gs/polGCZ2

**Comment by TheCSDev** [comment]
It appears I forgot to removed that one line of code I used to debug the mod and make sure the chunks are actually getting unsaved. I resolved it and published a beta release now. Thank you for letting me know about this. Have a great day.

**Comment by ardissaps** [comment]
Log spam gone now, thank you very much!
